services:
  readyapi-testrunner:
    image: smartbear/ready-api-soapui-testrunner:latest
    volumes:
      - ./project:/project  # Mount your ReadyAPI project folder
      - ./reports:/reports  # Mount a folder for test reports
      # - ./extensions:/ext # Uncomment and mount if you have extensions
      # - ./plugins:/root/.soapui/plugins # Uncomment and mount if you have plugins
    environment:
      - SLM_LICENSE_SERVER=https://api.manage.smartbear.com:443 # Replace with your license server details
      - API_KEY=${MY_API_KEY}
      # Project printable report
      - COMMAND_LINE= -f%reports% '-RProject Report' -FXML '-EDefault environment' '%project%/REST-sample-auotmation-project-readyapi.xml' # Replace with your test runner arguments
      # JUnit-Style report for automation
      # - COMMAND_LINE= -f%reports% '-RJUnit-Style HTML Report' -FHTML '-EDefault environment' '%project%/REST-sample-auotmation-project-readyapi.xml' 
      # Data export for automation
      # - COMMAND_LINE= -f%reports% '-RData Export' -FXML '-EDefault environment' '%project%/REST-sample-auotmation-project-readyapi.xml' 
      # Allure Report
      # - COMMAND_LINE= -f%reports% '-RAllure Report' -FXML '-EDefault environment' '%project%/REST-sample-auotmation-project-readyapi.xml' 

    # ports:
    #   - "8080:8080" # Example: if your project interacts with a service on a specific port