name: ReadyAPI Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull ReadyAPI Docker Image
        run: docker pull smartbear/ready-api-soapui-testrunner:latest

      - name: Run ReadyAPI Tests
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/REST-sample-auotmation-project-readyapi.xml":/project \
            -v "${{ github.workspace }}/reports":/reports \
            -v "${{ github.workspace }}/extensions":/extension \
            -e SLM_LICENSE_SERVER="https://api.slm.manage.smartbear.com:443" \
            -e API_KEY="${{ secrets.SMARTBEAR_API_KEY }}" \
            smartbear/ready-api-soapui-testrunner:latest \
            -f/reports \
            -R"JUnit-Style HTML Report" \
            -FHTML \
            -EDefault\ environment

      - name: Publish Test Results
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: ReadyAPI Test Results
          path: reports/**/*.xml
          reporter: java-junit
