name: ReadyAPI Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Pull ReadyAPI Docker Image
        run: docker pull smartbear/ready-api-soapui-testrunner:latest
      
      - name: Run ReadyAPI Tests
        run: |
          docker run \
            -v "${{ github.workspace }}/REST-sample-auotmation-project-readyapi.xml":/project \
            -v "${{ github.workspace }}/reports":/reports \
            -v="${{ github.workspace }}/extensions":/extension \
            -e SLM_LICENSE_SERVER="https://api.slm.manage.smartbear.com:443" \
            -e API_KEY="${{ secrets.SMARTBEAR_API_KEY }}" \